"""
services/idempotency_service.py
Royal Metal Allocation System — Python port

WHEN A REPEATED request_id MAY BE ANSWERED WITH THE STORED RESULT.

CLAUDE.md rule 12: "a repeat within the 900-second window returns the original
result rather than double-writing. This guards against double-clicks and
retries." Resolved 2026-09-22 in favour of that, over legacy's error — see the
note in repository/idempotency_repo.py.

The decision that needs a single home is not *how* to store a result but *who
may be given one back*, which is why this is a service rather than three copies
of the same four guards in the save, revise and submit paths.

THE GUARDS, AND WHY EACH ONE EXISTS:

  * A DIFFERENT USER NEVER REPLAYS. This is the one that matters. request_id is
    generated by the browser (api/allocations.js's newRequestId()), so it is
    guessable and is not a secret. Without this check, sending somebody else's
    id would hand back their audit id, record counts and totals — a disclosure,
    in a system where scope is otherwise enforced on every single request
    (rule 8). The repeat is still refused; it is simply not answered.

  * A DIFFERENT ENDPOINT NEVER REPLAYS. The three paths store three different
    shapes. Replaying a submission's payload into a save response would either
    raise or, worse, quietly return a result of the wrong kind.

  * AN UNREADABLE RECORD NEVER REPLAYS. Rows written by an earlier build have no
    response_json, or one this build cannot parse. Degrading to the duplicate
    error is always safe: it is what the caller used to get, and it never
    double-writes.

In every one of those cases the caller receives DUPLICATE_REQUEST exactly as
before. Refusing to replay is never the same as permitting a second write — the
id is spent either way, which is the whole point of the guard.
"""

import json
import logging

logger = logging.getLogger(__name__)


def replayable_result(entry, *, user_email: str, endpoint: str) -> dict | None:
    """The stored response for a repeated request_id, or None if it must not be
    replayed.

    `entry` is a RequestLog row (or None) from idempotency_repo.find_live_entry.
    A None return means "refuse as a duplicate", never "allow the write".
    """
    if entry is None:
        return None

    if entry.user_email != user_email:
        # Deliberately not logged with both addresses: this is reachable by
        # anyone guessing an id, and the log should not become a record of who
        # holds which request id.
        logger.warning("request_id replay refused: belongs to another account")
        return None

    if entry.endpoint != endpoint:
        logger.warning(
            "request_id replay refused: stored for %s, replayed at %s",
            entry.endpoint,
            endpoint,
        )
        return None

    if not entry.response_json:
        return None

    try:
        data = json.loads(entry.response_json)
    except (ValueError, TypeError):
        logger.warning("request_id replay refused: stored response is not valid JSON")
        return None

    return data if isinstance(data, dict) else None
